name: 📚 Documentation
description: Report an issue related to lingo-chat-api-server
title: "[Doc]: "
labels: ["documentation"]

body:
  - type: markdown
    attributes:
      value: |
        ## Background

        > 작성하려고 하는 문서에 대해 간결하게 설명해주세요.

  - type: markdown
    attributes:
      value: |
        ## Details(Todo List)

        - [ ] TODO
        - [ ] TODO
        - [ ] TODO

  - type: markdown
    attributes:
      value: |
        ## etc(optional)

        > 기타 자세한 Description, 관련된 Link 등이 있다면 작성해 주세요.